# Generated by Django 3.1.3 on 2020-12-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('members', models.IntegerField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('floor', models.IntegerField()),
                ('locationX', models.FloatField()),
                ('locationY', models.FloatField()),
                ('locationZ', models.FloatField()),
                ('connectPoints', models.TextField(blank=True)),
                ('connectMarkets', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.CharField(max_length=30)),
                ('background', models.TextField()),
                ('performance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=15)),
                ('temperature', models.FloatField()),
                ('startPoint', models.CharField(blank=True, max_length=10)),
                ('endPoint', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('president', models.CharField(max_length=10)),
                ('markImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('performance', models.TextField()),
                ('info', models.TextField()),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.professor')),
            ],
        ),
    ]
