# Generated by Django 3.1.3 on 2020-12-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='endPoint',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='visitor',
            name='startPoint',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
